[book]
authors = ["Yehuda Katz"]
language = "en"
src = "src"
title = "Color System Documentation"
site-url = "/algebraic/"

[output.html]
additional-js = ["src/js/mermaid.min.js", "src/js/mermaid-init.js"]
additional-css = ["src/css/color-system.css"]

