[book]
authors = ["Yehuda Katz"]
language = "en"
src = "src"
title = "Color System Documentation"

[output.html]
site-url = "/algebraic/"
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]
additional-css = ["css/color-system.css", "css/docs.css"]

